---
database:
  hosts:
    db01:
      ansible_host: db01
      ansible_python_interpreter: /usr/bin/python3
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 13.80.177.112
      ansible_port: 22
      ansible_ssh_user: jenkins
      #ansible_ssh_private_key_file: ~/.ssh/id_rsa_devops
  vars:
    ansible_python_interpreter: /usr/bin/python3
control:
  hosts:
    control:
      ansible_connection: local
webserver:
  hosts:
    app01:
      ansible_host: app01
  vars:
    ansible_python_interpreter: /usr/bin/python3